# Mount tasks - main.yml
---
- name: install required packages - mount (cifs)
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - cifs-utils
  when: mount_fstype == "cifs" or mount_fstype == "smb"

- name: install required packages - mount (nfs)
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nfs-common
  when: mount_fstype == "nfs"

- name: create mount credentials folder
  file:
    dest: /root/.mount_credentials
    owner: root
    group: root

- name: create mount credentials
  template:
    src: mount_credentials.j2
    dest: "/root/.mount_credentials/{{ mount_name }}_mount_credentials"
    owner: root
    group: root
    mode: 0600

- name: mount share (cifs)
  mount:
    path: "{{ mount_path }}"
    src: "{{ mount_share }}"
    fstype: cifs
    opts: "credentials=/root/.mount_credentials/{{ mount_name }}_mount_credentials,{{ mount_options }}"
    state: "{{ mount_state }}"
  when: mount_fstype == "cifs" or mount_fstype == "smb"

- name: mount share (nfs)
  mount:
    path: "{{ mount_path }}"
    src: "{{ mount_share }}"
    fstype: nfs
    opts: "{{ mount_options }}"
    state: "{{ mount_state }}"
  when: mount_fstype == "nfs"

- name: mount share (other)
  mount:
    path: "{{ mount_path }}"
    src: "{{ mount_share }}"
    fstype: "{{ mount_fstype }}"
    opts: "{{ mount_options }}"
    state: "{{ mount_state }}"
  when:
    - mount_fstype != "cifs"
    - mount_fstype != "smb"
    - mount_fstype != "nfs"